---
- hosts: all
  tags: ["common"]
  become: yes
  tasks:
    - name: Build hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_eth1.ipv4.address }} {{ hostvars[item].ansible_hostname }}"
        state: present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: Debug hosts
      debug:
        msg: "{{ item }} : {{ hostvars[item].ansible_eth1.ipv4.address }} : {{ hostvars[item].ansible_hostname }}"
      with_items: "{{ groups['all'] }}"

  roles:
    - { role: jpnewman.locale-timezone, tags: ["init"] }
    - { role: jpnewman.common, tags: ["init"] }
    - { role: jpnewman.java, tags: ["init"] }

- hosts: elk-server
  tags: ["elk_server"]
  become: yes
  roles:
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: jpnewman.elasticsearch, tags: ["elasticsearch"] }
    - { role: geerlingguy.elasticsearch-curator, tags: ["elasticsearch-curator"] }
    - { role: jpnewman.elk-kibana, tags: ["kibana"] }
    - { role: jpnewman.redis, tags: ["redis"] }
    - { role: jpnewman.elk-logstash-indexer, tags: ["logstash-indexer"] }
    - { role: jpnewman.elk-filebeat, tags: ["filebeat"] }
    - { role: jpnewman.elk-topbeat, tags: ["topbeat"] }
    # - { role: jpnewman.elk-packetbeat, tags: ["packetbeat"] }
    - { role: geerlingguy.elasticsearch-curator, tags: ["elasticsearch-curator"] }

- hosts: elk-log
  tags: ["elk-log"]
  become: yes

  tasks:
    - name: Install redis-tools, for testing
      apt: name=redis-tools
           state=installed
           update_cache=yes
           cache_valid_time=600

  roles:
    - { role: geerlingguy.security, tags: ['security'] }
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: jpnewman.elk-logstash-shipper, tags: ["logstash-shipper"] }
    - { role: jpnewman.elk-filebeat, tags: ["filebeat"] }
    - { role: jpnewman.elk-topbeat, tags: ["topbeat"] }
    - { role: jpnewman.elk-packetbeat, tags: ["packetbeat"] }

- hosts: test-app
  tags: ["test-app"]
  become: yes

  roles:
    - { role: jpnewman.elk-filebeat, tags: ["filebeat"] }
    - { role: jpnewman.elk-topbeat, tags: ["topbeat"] }
    - { role: jpnewman.elk-packetbeat, tags: ["packetbeat"] }

  tasks:
      # Vagrant inventory still uses 'ansible_ssh_*'
    - name: Fix Ansible SSH port / vagrant inventory bug. Ansible 2.3.0.0 synchronize module uses ansible_ssh_port and not ansible_port from vagrant_ansible_inventory. But uses ansible_host.
      set_fact:
          ansible_ssh_port: 22

    - name: Copy Test App
      synchronize:
        src: ../../files/test_app
        dest: /opt/
        archive: no
        recursive: yes
        rsync_opts:
          - "--no-motd"
          - "--exclude=.DS_Store"
          - "--exclude=.git"
          - "--exclude=__pycache__"
          - "--exclude=logs"
          - "--exclude=venv"

    - name: Fix Ansible SSH port / vagrant inventory bug. Ansible 2.3.0.0 synchronize module uses ansible_ssh_port and not ansible_port from vagrant_ansible_inventory. But uses ansible_host.
      set_fact:
          ansible_ssh_port: 2222

    - name: Install PIP
      apt:
        name: python3-pip
        state: installed
        update_cache: yes
        cache_valid_time: 600

    - name: Install Test App Requirements
      pip:
        executable: pip3
        requirements: /opt/test_app/requirements.txt

    - name: Scheduled test app
      cron:
        name: "test_app"
        job: "cd /opt/test_app && ./test_app.py > /dev/null"
