---
limits:
  - domain: '*'
    type: 'soft'
    item: 'nofile'
    value: 'unlimited'
  - domain: '*'
    type: 'hard'
    item: 'nofile'
    value: 'unlimited'
  - domain: 'root'
    type: 'soft'
    item: 'nofile'
    value: 'unlimited'
  - domain: 'root'
    type: 'hard'
    item: 'nofile'
    value: 'unlimited'
  - domain: 'redis'
    type: 'hard'
    item: 'nofile'
    value: '100000'
  - domain: 'redis'
    type: 'hard'
    item: 'nofile'
    value: '100000'
  - domain: 'elasticsearch'
    type: 'soft'
    item: 'nofile'
    value: 'unlimited'
  - domain: 'elasticsearch'
    type: 'hard'
    item: 'nofile'
    value: 'unlimited'
