---
filebeat_elasticsearch_host: 10.10.10.10:9200
filebeat_logstash_host: 10.10.10.11:5044

prospectors:
  - id: syslog
    paths:
    - log_paths:
        - /var/log/syslog
        - /var/log/auth.log
      document_type: syslog
    type: syslog
    app_id: artifactory
    elasticsearch_index: artifactory

  - id: varlog
    paths:
    - log_paths:
        - /var/log/*.log
      exclude_files:
        - "^syslog$"
        - "^auth.log$"
        - "^filebeat.log.*$"
        - "^topbeat.log.*$"
      document_type: log
    app_id: artifactory
    elasticsearch_index: artifactory

  - id: artifactory
    paths:
    - log_paths:
      - /opt/artifactory/logs/access.log
      document_type: artifactory-access
    app_id: artifactory
    elasticsearch_index: artifactory

  - id: tomcat
    paths:
    - log_paths:
      - /var/log/tomcat7/*.log
      document_type: tomcat
    multiline:
      pattern: '^([Jj]an(uary|uar)?|[Ff]eb(ruary|ruar)?|[Mm](a|ä)?r(ch|z)?|[Aa]pr(il)?|[Mm]a(y|i)?|[Jj]un(e|i)?|[Jj]ul(y)?|[Aa]ug(ust)?|[Ss]ep(tember)?|[Oo](c|k)?t(ober)?|[Nn]ov(ember)?|[Dd]e(c|z)(ember)?) ((0[1-9])|([12][0-9])|(3[01])|[1-9]), [0-9]{4} (2[0123]|[01]?[0-9]):?([0-5][0-9])(:?(([0-5]?[0-9]|60)([:.,][0-9]+)?)) (AM|PM)'
      negate: true
      match: after
    type: tomcat
    app_id: artifactory
    elasticsearch_index: artifactory

  - id: catalina
    paths:
    - log_paths:
      - /var/log/tomcat7/catalina.out
      document_type: catalina
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
    type: catalina
    app_id: artifactory
    elasticsearch_index: artifactory

    # Test App
  - id: gerrit-review
    paths:
    - log_paths:
      - /opt/test_app/logs/change-merged.log
      - /opt/test_app/logs/comment-added.log
      - /opt/test_app/logs/patchset-created.log
      document_type: gerrit_review_logs
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
    type: gerrit_review_logs
    app_id: gerrit
    elasticsearch_index: gerrit
